pts_blagues_Enila` = 0
pts_blagues_Jiss = 2
pts_blagues_Enila = 0
pts_blagues_ezak = 3
pts_blagues_mad2n = 28
pts_blagues_zarathustra = 3
pts_blagues_Jiss_ThemisEnculay = 1
pts_blagues_emeau_ = -1
pts_blagues_qolund = 1
pts_blagues_Horgh = -2
pts_blagues_sqwall = 2
pts_blagues_Flyers = 2
pts_blagues_EpicOut = 1
pts_blagues_Baboon = 11
a = 'return 2'
insultes = ['connard', 'sac \xc3\xa0 foutre', 'trou de balle', 'encul\xc3\xa9', "baiseur d'\xc3\xa2nes", 'enculeur de chameau', 'fils de pute', 'batard', 'kosovard', 'roux', 'bavarois', 'tatu', 'gros con', 'con de buse', 'couille de loup', "pine d'ours", 'garage a bite', 'suceur de queues', 'S\xc3\xa9golene', 'skaterboy', 'linuxien', 'keke tuning', 'fifi', 'vieux gland', 'noir']
['ezak', 'Tuna', 'Baboon'] = []
pts_blagues_kaze = 11
fatmeet_participants = set([])
pts_blagues_over = 6
pts_blagues_Tuna = 3
