0 = (0, 100, '^!$1={[a-zA-Z][a-zA-Z0-9_]*}[ ]*=$2={.*}$', Code('assign(arg1,eval(arg2))'))
1 = (0, 100, '^!p $1={.*}$', Code('eval(arg1)'))
2 = (0, 100, '^!help', Code("'RTFM: http://lerhino.fr:5678'"))
3 = (0, 100, '^!$1={[a-zA-Z][a-zA-Z0-9_]*}[ ]*$2={.*}$', Code('call_format(arg1,arg2)'))
4 = (0, 20, 'kiko[o]+', Code("rnd(['\x02\x034,1 KIKOOOOOOOOOOO !!!!!!o)))))))))))) \x0f', '\x02\x0311,6 KIKOOOOO !!!!!!!!o)))))))))) \x0f'])"))
5 = (0, 1, '.', Code("rnd(['oui', 'tout a fait', 'tg %s'%nick, 'suce moi %s' %nick, 'non', 'hmm', 'plutot pomper un ours', 'et ta soeur ?', 'paye ton cul %s' %nick, 'pas autant que ta mere', 'ou pas', 'oui da', 'et un mars', 'tout simplement', 'ou alors tu peux fermer ta gueule'])"))
6 = (0, 50, '\\b(gay|pd|homo|homosexuel)\\b', Code("rnd(['les pds sont gays', 'je suis hetero', 'je vous laisse entre filles'])"))
7 = (0, 5, '(er|\xc3\xa9|ez)$', Code('"poil au nez"'))
8 = (0, 5, '(us|uce)$', Code("rnd(['suce', 'ca rime avec suce', 'ca rime avec anus'])"))
9 = (0, 5, '(ou|oux)$', Code("'poil au genou'"))
10 = (0, 55, '$1={baise[r]?|nique[r]?|suce[r]?|defonce[r]?|troncher}', Code("rnd(['en parlant de %s, j\\'ai vu ta mere hier %s' %(arg1,nick), 'en parlant de ca, comment va ta soeur %s ?'%nick, 'd\\'ailleur j\\'ai %s ta mere %s'%(arg1,nick), 'j\\'aime %s'%arg1, 'je te %s %s au passage'%(arg1,nick)])"))
11 = (0, 80, '$1={\\d+ ?(seconde[s]?|minute[s]?)\\b}', Code("rnd(['%s c\\'est ton record au lit %s ?'%(arg1,nick), 'c\\'est a peu pres le temps qu\\'il me faut pour convaincre ta soeur, %s'%arg1, 'plus rapide que Usain Bolt !'])"))
12 = (0, 80, '$1={\\d+ ?(cm|m|mm)\\b}', Code("rnd(['%s c\\'est petit \xc3\xa7a'%arg1, 'ma bite fait %s'%arg1, '%s c\\'est ce qu\\'a pris ta m\xc3\xa8re hier soir %s'%(arg1,nick)])"))
13 = (0, 99, 'insulte $1={[^ ]+}\\b', Code(" '%s%s%s'%(rnd(['','putain de ','putain de bordel de ']),rnd(insultes),' '+arg1)"))
14 = (1, 20, '$1={.*}', Code('markov_answer(arg1,1)'))
15 = (1, 10, '$1={.*}', Code('markov_repeat(arg1,1)'))
16 = (1, 5, '$1={.*}', Code('log_answer(arg1,1)'))
17 = (0, 100, 'dis .*une quote', Code('quote_rnd()'))
18 = (0, 100, 'ajoute .*la quote $1={.*}', Code('quote_add(arg1);"Quote ajout\xc3\xa9e"'))
19 = (0, 100, '\\b(haha[ha]*|lol|mdr|trop fort|rofl)\\b $1={[^ ]+}', Code('(arg1 not in spectators or arg1==nick) or assign("pts_blagues_%s"%arg1,get("pts_blagues_%s"%arg1,0)+1); (arg1 not in spectators and " ") or "%s a %s point blagues"% (arg1,get("pts_blagues_%s"%arg1))'))
20 = (0, 100, '\\b(naze|bouh+|trop con)\\b $1={[^ ]+}', Code('arg1 not in spectators or assign("pts_blagues_%s"%arg1,get("pts_blagues_%s"%arg1,0)-1); (arg1 not in spectators and " ") or "%s a %s point blagues"% (arg1,get("pts_blagues_%s"%arg1))'))
21 = (1, 80, 'combien de $1={\\w+}', Code('"%d %s" % (random.randint(0,100),arg1)'))
22 = (1, 50, '(\\bmac|\\bapple\\b|\\biphone\\b|\\bipod\\b|\\bsteve jobs\\b)', Code('markov_repeat("merde",1)'))
23 = (1, 100, 'je veux .* fatmeet', Code('fatmeet_participants.add(nick); "%s veut aller au fatmeet !"%nick'))
24 = (1, 100, 'qui veut .* fatmeet', Code(' "%s veulent aller au fatmeet" % ",".join(fatmeet_participants)'))
25 = (1, 90, '^qui $1={(est|sera|serait|etait)} $2={.*} (ici|sur ce chan|dans ce chan)', Code(' "#personne# %s %s %s" % (arg1,arg2,rnd(["clairement","comme le dis ta mere","comme tout le monde sait","meme si on dirait pas","et oui"]))'))
26 = (1, 90, 'linux', Code('markov_repeat("merde",1)'))
27 = (1, 90, 'oui ou non', Code('random.choice(["oui","non","fais ce que tu veux je m\'en branle"])'))
28 = (0, 100, 'dessine.moi\\s+(un|une|le|la|les|des)\\s+$1={.*}', Code('dessine2(arg1,18,5)'))
29 = (0, 100, 'dessine.moi\\s+$1={http.*}', Code('dessine_url2(arg1,18,5)'))
30 = (1, 100, '^redessine', Code('redessine2()'))
35 = (0, 100, '^boire', Code('rnd(["oki doki","non, pas ce soir, tu m\xc3\xa9rites pas"])'))
36 = (1, 100, '^$1={[A-Z]\\d+}\\b', Code('bataille_joue(nick,arg1)'))
37 = (0, 100, '(la|ma) grille$', Code('bataille_grille(nick)'))
38 = (0, 100, 'joue a la bataille', Code('bataille_new(nick)'))
39 = (0, 100, 'peins.moi\\s+(un|une|le|la|les|des)\\s+$1={.*}', Code('peins2(arg1,18,5)'))
40 = (0, 100, 'kikoo $1={.*}$', Code(' "\\002"+(lambda y=(lambda i,j:(i,j if j<i else j+1)),s=random.choice,r=random.randrange:"".join("\\x03%02d,%02d"%y(r(16),r(15))+x for x in "Kik%s %s !!!!!! :o%s"%(r(5,10)*\'O\', arg1, r(5,10)*\')\')))()'))
